#!/usr/bin/env python3
"""
Student model deployment interface.

Aligned with eval_student_unseen_obj.sh:
    ++student.norm="ln"
    ++student.decoder.film_mlp=1

Assets loaded from export_dir/ (generated by test_rma.py --export_cfg_dir):
    student.yaml, student.ckpt    — student model config & weights
    normalizer.yaml, normalize.ckpt — observation normalizer config & state
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, Optional

import numpy as np
import torch as th
import yaml
from omegaconf import OmegaConf

from .se3 import SE3, assert_se3, step_towards


def _rot6d_from_R(R: np.ndarray) -> np.ndarray:
    """3x3 rotation matrix → 6D continuous representation (first two columns, row-major flatten)."""
    return np.asarray(R, dtype=np.float32).reshape(3, 3)[:, :2].reshape(6)


def _pose9d_from_se3(T: SE3) -> np.ndarray:
    """SE3 → [pos(3), rot6d(6)] = 9D."""
    assert_se3(T)
    pos = np.asarray(T[:3, 3], dtype=np.float32).reshape(3)
    rot6d = _rot6d_from_R(T[:3, :3])
    return np.concatenate([pos, rot6d]).astype(np.float32)


def _relative_pose9d_from_se3(goal_T: SE3, current_T: SE3) -> np.ndarray:
    """goal * inv(current) -> pose9d, aligned with training rel_goal_gt."""
    assert_se3(goal_T)
    assert_se3(current_T)
    T_rel = np.asarray(goal_T, dtype=np.float32) @ np.linalg.inv(np.asarray(current_T, dtype=np.float32))
    assert_se3(T_rel)
    return _pose9d_from_se3(T_rel)


# ---------------------------------------------------------------------------
#  Lightweight normalizer for deployment (no IsaacGym / gym dependency)
# ---------------------------------------------------------------------------

class _DeployNormalizer:
    """Reproduces EnvNormalizer.normalize_obs logic using exported yaml+ckpt."""

    def __init__(self, yaml_path: Path, ckpt_path: Path, device: str):
        with open(yaml_path) as f:
            cfg = yaml.safe_load(f)
        self.device = th.device(device)
        self.eps = float(cfg.get("obs_eps", 1e-6))

        constlist = set(cfg.get("constlist", []))
        stats = cfg.get("stats", {}) or {}

        self._const: Dict[str, tuple] = {}
        for k in constlist:
            s = stats.get(k)
            if s is not None and len(s) == 2:
                mean = th.tensor(s[0], dtype=th.float32, device=self.device)
                std = th.tensor(s[1], dtype=th.float32, device=self.device)
                self._const[k] = (mean, std)

        self._running: Dict[str, tuple] = {}
        sd = th.load(str(ckpt_path), map_location="cpu").get("normalizer", {})
        for key in list(sd.keys()):
            if key.startswith("obs_rms.") and key.endswith(".mean"):
                obs_key = key[len("obs_rms."):-len(".mean")]
                var_key = f"obs_rms.{obs_key}.var"
                if obs_key not in constlist and var_key in sd:
                    self._running[obs_key] = (
                        sd[key].to(self.device),
                        sd[var_key].to(self.device),
                    )

    def normalize(self, obs: Dict[str, th.Tensor]) -> Dict[str, th.Tensor]:
        """Normalize an obs dict in-place-safe manner."""
        out = {}
        for k, v in obs.items():
            if k in self._const:
                mean, std = self._const[k]
                out[k] = (v - mean) * th.reciprocal(std + self.eps)
            elif k in self._running:
                mean, var = self._running[k]
                out[k] = (v - mean) * th.reciprocal(th.sqrt(var) + self.eps)
            else:
                out[k] = v
        return out

    def normalize_cloud(self, ref_key: str, cloud: th.Tensor) -> th.Tensor:
        """Normalize a point cloud using the same constant params as *ref_key*."""
        if ref_key in self._const:
            mean, std = self._const[ref_key]
            return (cloud - mean) * th.reciprocal(std + self.eps)
        return cloud


# ---------------------------------------------------------------------------
#  Public config & interface
# ---------------------------------------------------------------------------

@dataclass
class DywaStudentPolicyConfig:
    """Configuration aligned with eval_student_unseen_obj.sh semantics.

    ``export_dir`` must contain:
        student.yaml / student.ckpt   — student model
        normalizer.yaml / normalize.ckpt — observation normalizer
    """
    export_dir: Path
    device: str = "cuda:0"
    cloud_n: int = 512
    block_assets_dir: Optional[Path] = None

    # eval script overrides
    norm: str = "ln"                          # ++student.norm="ln"
    film_mlp: bool = True                     # ++student.decoder.film_mlp=1

    # nominal offset from block frame to EE frame
    T_block_ee_nominal: Optional[SE3] = None

    # real-robot observation callbacks (world/base frame, SI units)
    get_partial_cloud_world: Optional[Callable[[], np.ndarray]] = None  # → (N,3)
    get_robot_state: Optional[Callable[[], np.ndarray]] = None          # → (14,)
    get_hand_state: Optional[Callable[[], np.ndarray]] = None           # → (9,)

    # action interpretation (first 6 dims → EE delta)
    delta_scale_pos: float = 0.02
    delta_scale_rot: float = 10.0 / 180.0 * np.pi


class DywaStudentPolicyInterface:
    """Student model inference — loads exported assets, normalizes obs, outputs EE target.

    Lifecycle:
        1. __init__  — loads model + normalizer from export_dir
        2. reset_episode()  — call once per episode
        3. compute_action(…) — call each control step; returns dict with ``ee_target_T_world``
    """

    def __init__(self, cfg: DywaStudentPolicyConfig):
        self.cfg = cfg
        self.device = th.device(cfg.device)
        export_dir = Path(cfg.export_dir)

        # ---- student model ----------------------------------------------------
        from dywa.exp.train.distill import StudentAgentRMA  # type: ignore

        student_omega = OmegaConf.load(str(export_dir / "student.yaml"))
        student_omega.norm = cfg.norm
        student_omega.decoder.film_mlp = cfg.film_mlp
        student_omega.batch_size = 1

        base = OmegaConf.structured(StudentAgentRMA.StudentAgentRMAConfig())
        OmegaConf.set_struct(base, False)
        merged = OmegaConf.merge(base, student_omega)
        student_cfg = OmegaConf.to_object(OmegaConf.structured(merged))

        self.student = StudentAgentRMA(student_cfg, writer=None, device=self.device)
        self.student.to(self.device)

        from dywa.src.train.ckpt import load_ckpt  # type: ignore

        load_ckpt(
            dict(student=self.student),
            str(export_dir / "student.ckpt"),
            strict=False,
            exclude_keys=["history_tokenizer.history", "aggregator.aggregator.memory"],
        )
        self.student.eval()

        # ---- normalizer -------------------------------------------------------
        self._normalizer = _DeployNormalizer(
            export_dir / "normalizer.yaml",
            export_dir / "normalize.ckpt",
            cfg.device,
        )

        # ---- internal state ---------------------------------------------------
        self._action_size = int(student_cfg.action_size)
        self._use_gpcd = bool(student_cfg.use_gpcd)
        self._infer_need_rel_goal_gt = bool(
            getattr(student_cfg, "merge_pose_pred", False)
        )
        self._prev_action = np.zeros((self._action_size,), dtype=np.float32)
        self._needs_reset = True

        if cfg.T_block_ee_nominal is None:
            T = np.eye(4, dtype=np.float32)
            T[:3, 3] = [0.0, 0.0, 0.10]
            self.T_block_ee_nominal = T
        else:
            self.T_block_ee_nominal = np.asarray(cfg.T_block_ee_nominal, dtype=np.float32)
            assert_se3(self.T_block_ee_nominal)

    # ---- public API -----------------------------------------------------------

    def reset_episode(self) -> None:
        self._prev_action.fill(0.0)
        self._needs_reset = True

    def compute_action(
        self,
        block_type: str,
        current_T_world_block: SE3,
        target_T_world_block: SE3,
    ) -> Dict:
        assert_se3(current_T_world_block)
        assert_se3(target_T_world_block)

        T_nom = np.asarray(target_T_world_block, dtype=np.float32) @ self.T_block_ee_nominal
        assert_se3(T_nom)

        # 1) build & normalize observation
        obs = self._build_obs(
            target_T=np.asarray(target_T_world_block, dtype=np.float32),
            current_T=np.asarray(current_T_world_block, dtype=np.float32),
        )
        obs = self._normalizer.normalize(obs)

        if self._use_gpcd:
            gc_raw = self._load_goal_cloud_world(
                str(block_type),
                np.asarray(target_T_world_block, dtype=np.float32),
            )
            gc = th.from_numpy(gc_raw[None, :, :]).to(self.device)
            obs["goal_cloud"] = self._normalizer.normalize_cloud("partial_cloud", gc)

        # 2) forward pass (reset on first call, then incremental)
        with th.no_grad():
            if self._needs_reset:
                output = self.student.reset(obs)
                self._needs_reset = False
            else:
                output, _ = self.student._forward_impl(obs)
        vec = output[0, 0].float().cpu().numpy().reshape(-1)

        # 3) interpret first 6 dims as EE delta on nominal target
        T_cmd = self._apply_delta(vec, T_nom)
        T_smooth = step_towards(
            T_nom, T_cmd, max_translation=0.01, max_rotation_rad=10.0 / 180.0 * np.pi
        )

        # 4) update previous_action buffer
        n = min(vec.size, self._action_size)
        self._prev_action[:n] = vec[:n]

        return {
            "ee_target_T_world": T_smooth,
            "gripper_width": 0.05,
            "raw_action": vec.tolist(),
        }

    # ---- internals ------------------------------------------------------------

    def _build_obs(self, target_T: SE3, current_T: SE3) -> Dict[str, th.Tensor]:
        abs_goal = _pose9d_from_se3(np.asarray(target_T, dtype=np.float32))
        rel_goal_gt = _relative_pose9d_from_se3(
            np.asarray(target_T, dtype=np.float32),
            np.asarray(current_T, dtype=np.float32),
        )
        hand = (
            np.asarray(self.cfg.get_hand_state(), dtype=np.float32).reshape(9)
            if self.cfg.get_hand_state
            else np.zeros(9, dtype=np.float32)
        )
        robot = (
            np.asarray(self.cfg.get_robot_state(), dtype=np.float32).reshape(14)
            if self.cfg.get_robot_state
            else np.zeros(14, dtype=np.float32)
        )
        pc = (
            self._sample_cloud(self.cfg.get_partial_cloud_world())
            if self.cfg.get_partial_cloud_world
            else np.zeros((self.cfg.cloud_n, 3), dtype=np.float32)
        )
        out: Dict[str, th.Tensor] = {
            "abs_goal": th.from_numpy(abs_goal[None, :]).to(self.device),
            "hand_state": th.from_numpy(hand[None, :]).to(self.device),
            "robot_state": th.from_numpy(robot[None, :]).to(self.device),
            "previous_action": th.from_numpy(self._prev_action[None, :].copy()).to(self.device),
            "partial_cloud": th.from_numpy(pc[None, :, :]).to(self.device),
        }
        if self._infer_need_rel_goal_gt:
            rel_goal_gt = _relative_pose9d_from_se3(
                np.asarray(target_T, dtype=np.float32),
                np.asarray(current_T, dtype=np.float32),
            )
            out["rel_goal_gt"] = th.from_numpy(rel_goal_gt[None, :]).to(self.device)
        return out

    def _sample_cloud(self, pc: np.ndarray) -> np.ndarray:
        pc = np.asarray(pc, dtype=np.float32).reshape(-1, 3)
        n = max(1, self.cfg.cloud_n)
        if pc.shape[0] == 0:
            return np.zeros((n, 3), dtype=np.float32)
        idx = np.random.choice(pc.shape[0], size=n, replace=(pc.shape[0] < n))
        return pc[idx]

    def _load_goal_cloud_world(self, object_id: str, T_world_obj: SE3) -> np.ndarray:
        n = self.cfg.cloud_n
        if not self.cfg.block_assets_dir:
            return np.zeros((n, 3), dtype=np.float32)
        obj_path = Path(self.cfg.block_assets_dir) / f"{object_id}.obj"
        if not obj_path.exists():
            return np.zeros((n, 3), dtype=np.float32)
        try:
            import trimesh  # type: ignore
        except ImportError:
            return np.zeros((n, 3), dtype=np.float32)
        mesh = trimesh.load(str(obj_path), force="mesh")
        if isinstance(mesh, trimesh.Scene):
            mesh = trimesh.util.concatenate(list(mesh.geometry.values()))
        if not hasattr(mesh, "vertices") or mesh.vertices.size == 0:
            return np.zeros((n, 3), dtype=np.float32)
        pts, _ = trimesh.sample.sample_surface(mesh, n)
        pts = np.asarray(pts, dtype=np.float32)
        pts -= pts.mean(axis=0)
        R = np.asarray(T_world_obj[:3, :3], dtype=np.float32)
        t = np.asarray(T_world_obj[:3, 3], dtype=np.float32)
        return ((R @ pts.T).T + t).astype(np.float32)

    def _apply_delta(self, vec: np.ndarray, T_nom: SE3) -> SE3:
        d = np.zeros(6, dtype=np.float32)
        if vec.size >= 6:
            d[:] = vec[:6]
        dp = d[:3] * self.cfg.delta_scale_pos
        dr = d[3:6] * self.cfg.delta_scale_rot

        ang = float(np.linalg.norm(dr))
        if ang < 1e-9:
            R_delta = np.eye(3, dtype=np.float32)
        else:
            axis = dr / (ang + 1e-12)
            K = np.array(
                [[0, -axis[2], axis[1]], [axis[2], 0, -axis[0]], [-axis[1], axis[0], 0]],
                dtype=np.float32,
            )
            R_delta = np.eye(3, dtype=np.float32) + np.sin(ang) * K + (1 - np.cos(ang)) * (K @ K)

        T = np.asarray(T_nom, dtype=np.float32).copy()
        T[:3, :3] = (R_delta @ T[:3, :3]).astype(np.float32)
        T[:3, 3] = (T[:3, 3] + dp).astype(np.float32)
        assert_se3(T)
        return T


__all__ = [
    "DywaStudentPolicyConfig",
    "DywaStudentPolicyInterface",
]
